### PR TITLE
Add i18n Support

### PR DESCRIPTION
**Pull request by rcmurphy**
* Adds i18n support
* Makes some small grammatical / phrasing tweaks to existing messages.

### CODE REVIEW

**Comment by safwanrahman** [comment]
Thanks for the PR! But I was wondering if we should keep the `.po` file in package! I do not have any idea about localization in django package.

**Comment by rcmurphy** [comment]
My understanding is yes, we should check in the mo and po files, as the po files are what actually drive it... Otherwise you need to run `django-admin compilemessages` before starting.

**Comment by rcmurphy** [comment]
Gentle bump!

**Comment by ahivert** [comment]
Yes the package should store po/mo files, you can check how Wagtail (django CMS) handle that.
https://github.com/wagtail/wagtail/tree/master/wagtail/locales/locale

To make this PR complete maybe we can add at least another language to have at least one example. I can do French one as I am going to need it :)

**Comment by mambasoft** [comment]
Hi, I'm also interested in this feature and can provide italian translations. Thanks!

**Comment by safwanrahman** [comment]
This looks good to me! Sorry it took so long to get it merged. I had some busy time last couple of months, so could not lookover the projects. Thanks @rcmurphy 💯🚀

**Pull request merged**
