### PR TITLE
Fix django 19x compat

### PR DESCRIPTION
**Pull request by jamaalscarlett**

### CODE REVIEW

**Comment by jamaalscarlett** [comment]
@safwanrahman

**Comment by safwanrahman** [comment]
@jamaalscarlett Hi, Thanks for the patch. Can you please remove the merge commit? and the other unnecessary commit?

**Comment by jamaalscarlett** [comment]
@safwanrahman the commit has been cleaned up

**Comment by safwanrahman** [comment]
It should work as mentioned above. so merging.
Sorry for the delay @jamaalscarlett.

**Comment by arogachev** [comment]
Confirm it works with Django 1.9.5 (had to grab these changes from master after 0.2.0 release).

**Pull request merged**
