### PR TITLE
Fixed #16: Better way to store webpush data in DOM

### LINKED ISSUE #16: Better way to store webpush data in DOM
In `webpush.html` template used by `{% webpush %}` template tag there is `div` element storing some webpush related data:

```python
<div id="webpush-data" {% if group %} data-group="{{ group }}" {% endif %} data-url="{{ url }}" hidden></div>
```

**1)** If this tag will be included in `head` section (and README says to add it there), then to have `div` inside HTML `head` tag will be semantically incorrect. Mozilla recognizes that and automatically moves it to `body` section during page loading. One more disadvantage is you can't register any scripts after `{% webpush %}`. For example, I can't write that:

```python
<head>
    {% webpush %}
    <script src="{% static 'core/js/custom.js' %}"></script>
</head>
```

`custom.js` will be ignored and not loaded at all.

**2)** It's incorrect to mix script declarations and elements storing data in one place. Also this element is tightly coupled and used with `{% webpush_button %}` tag, why not place it there? This is more appropriate place.

**3)** Having a `div` for only storing value from server probably is not the best choice. Hidden input with data attributes will be enough, but if we use it in `{% webpush_button %}`, why not use existing elements for that such as button itself?

### PR DESCRIPTION
**Pull request by arogachev**
Fixed #16: Better way to store webpush data in DOM

Additional notes:

- Fixed some code style problems in `webpush_notifications.py`:
  - Removed unused imports.
  - Fixed indendation.
  - Consistency in quotes usage (single quotes).
  - Fixed dictionary formatting.
- Removed unnecessary spaces around `data-group` attribute (they already exist around `if`) in `webpush_button.html`.
- Removed unncessary linebreaks in `webpush.html`.

### CODE REVIEW

**Comment by safwanrahman** [comment]
So the fact is that, do everyone will use our webpush button or not. I would be glad if you can find a way to include it in the header.

**Comment by arogachev** [comment]
> I would be glad if you can find a way to include it in the header.

As I said in the issue, including it in header that way is semantically incorrect.

> do everyone will use our webpush button or not

I think it's premature optimization. Currently extension pretty much forces user to use this button. The current implementation is very tightly with the button, so user either needs to accept it or rewrite js fully to fit his needs. We can replace it with hidden input or even leave as div, but what's the point? Everything in current implementation is built on top of this button.

When you decide to make it optional or remove it completely so extension provides only basic subscribing functionality and how to trigger it from interface will be user's decision (should be implemented by him) - that's when you need worry about. Along with it you can refactor the way data is passed from server.

And the main goal is to fix incorrect semantics and allow user to register scripts after `{% webpush %}` tag.

**Comment by safwanrahman** [comment]
Like you explanation. Thanks @arogachev for explaining. I will review the PR later today

**Comment by arogachev** [comment]
@safwanrahman OK. I'll add more issues about JS related problems.

**Comment by safwanrahman** [comment]
Code looks Good. I will check tomorrow in browser then merge it.
Thanks @arogachev for the Pull Request

**Comment by safwanrahman** [comment]
Sorry, could not get time. going to do it tomorrow, Friday (Week end here)

**Comment by safwanrahman** [comment]
Sorry for the delay. It was quite a busy week!
I have tested in and it works without any problem.
So lets merge it!
Thanks @arogachev

**Pull request merged**
