### PR TITLE
Fix bug when saving a SubscriptionForm

### PR DESCRIPTION
**Pull request by elishowk**
Bug = forgetting 'browser' in the Form made all model saved without 'browser'

### CODE REVIEW

**Comment by safwanrahman** [comment]
I intentionally removed the browser. It was needed when chrome needed to be handeled separately.

Can you explain if browser is needed in the case?

**Comment by elishowk** [comment]
The idea here is to separate different browser subscriptions : when subscribed in firefox, you don't want to be subscribed in chrome too.

**Comment by safwanrahman** [comment]
I understand. But how to differenciate between browsers from user point of view?
I can subscribe to Firefox in one device and subscribe in Chrome in other device.

**Comment by elishowk** [comment]
This patch was proposed because I thought it was an involuntary mistake not to save this 'browser' column. The model SubscriptionInfo and webpush.js both handle 'browser', and only the form forgot it.

My comprehension of this (sorry for my english) : if you don't store the browser short-name in the Subscription info, you'll display 'subscribed' in every browser, et you'll have the user think he/she'll receive notifications in chrome, even if for example he/she removed firefox from its computer (and vice-versa). But it's impossible du to each browser storing its own authorization tokens for the serviceworker to authorize displaying push notifications. Each browser needs it's own authorization and the model Subscription info should reflect this choices. Don't you think ?

I think it's a matter of choice of implementation to display to the user whether or not the current browser is subscribed.

But again in our use-case, webpush.js differentiate browser every time we send information to the server, and the model SubscriptionInfo never saves it :

JS : https://github.com/safwanrahman/django-webpush/blob/master/webpush/static/webpush/webpush.js#L157
Model : https://github.com/safwanrahman/django-webpush/blob/master/webpush/models.py#L12

**Comment by elishowk** [comment]
Moreover, I can't find any example of push notification authorization state that is common to every browser in the examples at https://pwa.rocks

**Comment by safwanrahman** [comment]
Understand your conern!
Thanks a lot @elishowk 
r+

**Comment by elishowk** [comment]
Cool, when do you plan on releasing this version on https://pypi.org/project/django-webpush/ ?

**Pull request merged**
