### PR TITLE
Cleaned up for loops.

### PR DESCRIPTION
**Pull request by jamaalscarlett**

### CODE REVIEW

**Comment by safwanrahman** [comment]
Hi @jamaalscarlett , Thanks for the Pull Request. Do you think there will not be any performance issue while there is a large number of subscription?

**Comment by jamaalscarlett** [comment]
Do you have specific examples of the slow down?  Either way you are iterating over a list.

**Comment by jamaalscarlett** [comment]
The true slowdown will occur when you do the initial query, not when you iterate through the data.

**Comment by safwanrahman** [comment]
While iterating over a large list of subscription object, I have seen that the Memory usage become high. So I have taken this approach about loop through indexing number. Do you think any other approach for iterating long list?

**Comment by safwanrahman** [comment]
Oh. Got it. Thanks @jamaalscarlett

**Pull request merged**
