### PR TITLE
Updated readme.md to include support for iOS16.4+

### PR DESCRIPTION
**Pull request by DartLazer**
Since the library now also works on Apple devices on iOS 16.4 + I've updated the readme to reflect this.

### CODE REVIEW

**Comment by safwanrahman** [comment]
Thanks @DartLazer

**Comment by Choieuntaek** [comment]
Hello, In order to use it in ios, what additional settings do I need?

**Comment by DartLazer** [comment]
For me it worked out of the box after using the settings from the Readme!

**Comment by Choieuntaek** [comment]
ah ok... um.. I'll delete it and reinstall it.
I did upgrade but, it doesn't work..

**Pull request merged**
