### PR TITLE
Add on_delete to ForeignKeys

### PR DESCRIPTION
**Pull request by neonwarp**
Since Django 2.0 on_delete is required so I added it to the old default as CASCADE.

### CODE REVIEW

**Comment by safwanrahman** [comment]
any migration needed?

**Comment by neonwarp** [comment]
Sorry I forgot to add it to git. I edited the initial script if that is okay.

**Comment by mayait** [comment]
Any plan to deploy this update?

**Comment by safwanrahman** [comment]
@neonwarp Any new migration is needed or need to add it in existing migrations?
As existing migration will not run anytime in the production environment.
Do you know if its handeled in the database end or in the django end?

**Comment by neonwarp** [comment]
I updated the initial script so it adds the `on_delete` to the fields and I believe it is handled in Django. Before v2 it was default to CASCADE so technically it should be the same but v2 now requires the attribute when defining a FK.

Maybe it is better to keep it in a new migration script although I think one should just do it and the package should come with the initial migration script but this is for you to decide :)

**Comment by safwanrahman** [comment]
It seems like its needed to be in the initial migration and django handle it form their end, not the database end!
Thanks for your PR @neonwarp 
r+

**Pull request merged**
