### PR TITLE
Support for Django 4.1

### PR DESCRIPTION
**Pull request by clearminds**
contextfunction has been renamed to pass_context

### CODE REVIEW

**Comment by safwanrahman** [comment]
Can you make it backward compitable?

**Comment by clearminds** [comment]
no clue how that is going to be possible to do since it is a decorator :/

**Comment by clearminds** [comment]
@safwanrahman ok, should be updated now with code that is backwards compatible

**Comment by clearminds** [comment]
@safwanrahman should I give up on using this library and move to something else?

**Comment by drien** [comment]
I forked and made these same changes myself before seeing this PR, everything seems to work properly.

I also removed the unused `arrow` import, since it's not actually used anywhere and not declared as a dependency.

**Pull request merged**
